### ISSUE TITLE
windows 无法下载

### ISSUE THREAD

**Issue by BlackTravel** [dxsooo/VideoDownload#10]
命令输入 ：
D:\TikTokDownload-main>TikTokDownload -u https://v.douyin.com/rwTTg5U/ -m yes

########################################################################################################################
错误 ：
[   💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🚩   ]:目前 13033 版本已是最新
Traceback (most recent call last):
  File "TikTokDownload\TikTokDownload.py", line 138, in <module>
  File "TikTokDownload\TikTokDownload.py", line 110, in video_download
IndexError: list index out of range
[18332] Failed to execute script TikTokDownload

**Comment by dxsooo** [comment]
你贴的错误信息应该也不是我代码的信息

目前支持的抖音视频需要是视频播放链接如：https://www.douyin.com/video/7158766931799985444

对于  https://v.douyin.com/rwTTg5U/  这种形式的链接（这种是用户页面），本项目当前不支持
